config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shows#index'
  get '/search', to: 'shows#search', as: 'search'

  get '/show/:id', to: 'shows#show', as: 'show'
  get '/add', to: 'shows#create', as: 'add_show'
  get 'auth/:provider/callback', to: 'users#callback', as: 'callback'
  get '/user/:username', to: 'users#show', as: 'user'
  delete '/logout', to: 'users#destroy', as: 'logout'


  get 'profile', to: 'users#profile', as: 'profile'

  post '/recommend/:show', to: 'shows#recommend', as: 'recommend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :show, counter_cache: true
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :recommendations, ->{order(created_at: :desc)}

  def self.save_show(data)
    show = Show.where(title: data['name']).first_or_initialize
    show.title = data['name']
    show.premiere_on = data['premiered']
    show.official_site = data['officialSite']
    show.imdb = data['externals']['imdb']
    show.network = data['network']['name']
    show.country = data['network']['country']['code']
    show.status = data['status']
    show.runtime = data['runtime']
    show.days = data['schedule']['days']
    show.medium_image = data['image']['medium']
    show.large_image = data['image']['original']
    show.summary = data['summary']
    show.genre = data['genres']
    show.save!
    show
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recommendations, ->{order(created_at: :desc)}

  def self.save_user_data(data)
    user = User.where(username: data.nickname).first_or_initialize
    user.username = data.nickname
    user.image = data.image
    user.description = data.description
    user.twitter = data.urls['Twitter']
    user.website = data.urls['Website']
    user.location = data.location
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.includes(:recommendations).find_by(id: session[:user])
  end

  def authentication_required
       redirect_to root_url, error: 'Please log in to continue' unless current_user
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authentication_required, only: [:recommend]
  
  def index
    @shows = Show.order(created_at: :desc).all
  end

  def show
    @show = Show.find_by(id: params[:id])
    redirect_to root_url if @show.nil?
  end

  def create
    query = params[:show]
    response = Tvmaze::GetShowData.new.call(query)
    Show.save_show(response)
    redirect_to root_url
  end

  def recommend
    Recommendation
        .where(show_id: params[:show], user_id: current_user.id)
        .find_or_create_by!(show_id: params[:show], user_id: current_user.id)
    redirect_to show_url(params[:show])
  end

  def search
    @shows = Show.where('title ILIKE ?', "%#{params[:query]}%")
    render 'shows/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authentication_required, except: [:callback]

  def callback
    user = User.save_user_data(user_info)
    session[:user] = user.id
    redirect_to root_url
  end

  def show
    @user = User.find_by(username: params[:username])
    @shows = Show.all
  end

  def profile
    @user = current_user
    render 'users/show'
  end

  def destroy
    session[:user] = nil
    redirect_to root_url
  end


  private

  def user_info
    request.env['omniauth.auth']['info']
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
  def show_recommended?(show_id)
    Recommendation.where(show_id: show_id).empty?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta class="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Showguide</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-3">
    <a class="navbar-brand" href="<%= root_url %>"><img src="<%= image_path 'logo.png' %>" class="logo"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center pt-1" id="navbar">
      <ul class="navbar-nav middle-menu">
        <li class="nav-item"><a class="nav-link" href="<%= root_url %>">Shows</a></li>
        <!-- <li class="nav-item"><a class="nav-link" href="#">People</a></li>-->
      </ul>

      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <form method="get" action="<%= search_url %>">
            <div class="input-group">
              <input type="text" class="form-control" name="query" placeholder="Search For TV show">
              <div class="input-group-append">
                <button class="btn btn-secondary" type="submit" id="submit"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </form>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link" href="<%= profile_url %>">My Profile</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_url, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="ml-1 nav-link btn btn-info text-white" href="/auth/twitter">Log In With Twitter</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= yield %>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/partials/_notification.html.erb
<% flash.each do |key, message| %>
  <div class="row">
    <div class="col-md-12">
      <p class="alert alert-<%= key %>"><%= message %></p>
    </div>
  </div>
<% end %>

app/views/shows/index.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-10 mt-3 pt-5">
      <p class="text-white lead font-weight-bold text-center">
        Showguide is a community of TV show buffs and connoisseurs where we
        share and recommend TV shows we love.
      </p>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-md-2 font-weight-bold text-uppercase pt-2">
      Add A TV Show
    </div>
    <div class="col-md-7">
      <form method="get" action="<%= add_show_path %>">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="TV Show's name" name="show">
          <div class="input-group-append">
            <button class="btn btn-secondary" type="submit" id="submit">Add</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <% @shows.each do |show| %>
      <a href="<%= show_url(show) %>"><img src="<%= image_path show.medium_image %>"></a>
    <% end %>
  </div>
</div>

app/views/shows/show.html.erb
<div class="container-fluid">
  <div class="row show-header p-5" style="background-image: url(<%= image_path @show.large_image %>)"></div>
  <div class="container pt-2">
    <div class="row">
      <div class="col-md-3">
        <div class="row">
          <img src="<%= image_path @show.medium_image %>" class="img-fluid d-none d-sm-block">

          <div class="col-md-9 border mt-2 rounded font-weight-bold small">
            <p>
              <a href="<%= @show.official_site %>" target="_blank">
              <i class="fas fa-arrow-alt-circle-right"></i> Official site</a>
            </p>
            <p>
              <a href="https://imdb/title/<%= @show.imdb %>" target="_blank">
                <i class="fab fa-imdb"></i> IMDB
              </a>
            </p>
            <p>
              <a href="https://www.youtube.com/results?search_query=<%= URI.encode(@show.title) %>+trailer" target="_blank">
                <i class="fab fa-youtube"></i>Trailer<i class="fas fa-external-link-alt text-muted pl-2"></i>
              </a>
            </p>
          </div>
        </div>
      </div>


      <div class="col-md-6 p-3">
        <h2 class="font-weight-bold pb-3"><%= @show.title %></h2>
        <div class="font-weight-normal">
         <%= simple_format(@show.summary) %>
        </div>
      </div>


      <div class="col-md-3 p-2">
        <div class="row">
          <div class="col-md-9 py-2 small mb-3 rounded">
            <p><span class="font-weight-bold">Network: </span> <%= @show.network %> (<%= @show.country %>)</p>
            <p><span class="font-weight-bold">Premiered: </span> <%= @show.premiere_on.strftime("%Y") %> </p>
            <p><span class="font-weight-bold">Status: </span> <%= @show.status %></p>
            <p><span class="font-weight-bold">
              Schedule: </span> <%= @show.days.to_sentence %> (<%= @show.runtime %> min)
            </p>
            <p><span class="font-weight-bold">Genre: </span> <%= @show.genre.to_sentence %></p>
            <p class="font-weight-bold">
              <%= pluralize(@show.recommendations_count, 'guide') %> recommend this</p>
            </p>
          </div>

          <div class="col-md-10">
            <% if current_user && show_recommended?(@show.id) %>
            <%= link_to 'Recommend', recommend_url(@show.id), method: :post,
                        class: 'btn btn-block btn-success font-weight-bold text-white' %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-3">
      <img src="<%= @user.image %>" class="img-fluid border rounded-circle">
    </div>

    <div class="col-md-7 pt-5 small">
      <h4 class="text-white font-weight-bold"><%= @user.username.capitalize %></h4>
      <p><%= @user.description %></p>
      <p>
        <span class="location">
          <i class="fas fa-map-marker"></i> <%= @user.location %> &nbsp;
        </span>

        <span>
           <a href="<%= @user.website %>" target="_blank"> <i class="fas fa-link"></i> Personal Website</a> &nbsp;
        </span>

        <span>
           <a href="<%= @user.twitter %>" target="_blank"><i class="fab fa-twitter"></i> Twitter</a>
        </span>
      </p>
    </div>
  </div>

  <div class="row pt-4">
    <h5 class="col-md-8 text-uppercase font-weight-bold small my-3">My Recommendations</h5>
  </div>
  <div class="row">
    <% @user.recommendations.each do |recommendation| %>
      <a href="<%= show_url(recommendation.show_id) %>"><img src="<%= image_path recommendation.show.medium_image %>"></a>
    <% end %>
  </div>
</div>